Tons of stuff
- More apps installed automatically
- Beautified output of install script
- Cleaner .bashrc, moved stuff to .bash_aliases and .bash_profile
- Disabled YCM auto install, because using nvim nowadays
- Tmux shows prefix on the info pane when prefix hotkey is pressed

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,28 +1,19 @@
 #!/bin/bash
+
 # Helper ANSI colors
 RED='\033[0;31m'
+GREEN='\033[0;32m'
+YELLOW='\033[0;33m'
 NC='\033[0m' # No Color
-USE_NVIM=1 # No Color
-USE_VIM=0 # No Color
+USE_NVIM=1 
 
 # creates symlinks for desired files from home to specified directory
-
 dir=~/dotfiles
 olddir=~/.dotfiles.bak
 
-# install GTK3 config
-unamestr=`uname`
-if [[ "$unamestr" == 'Linux' ]]; then GNOME_CONFIG=".config/gtk-3.0"
-    mkdir ~/$GNOME_CONFIG -p
-    ln -s $dir/$GNOME_CONFIG/gtk.css ~/$GNOME_CONFIG/gtk.css
-fi;
-
-#install git-completion
-cd $dir
-curl https://raw.github.com/git/git/master/contrib/completion/git-completion.bash -OL
-
 # list of files/folders to symlink in homedir
 declare -a files=(
+"agignore"
 "bashrc" "bash_profile" "bash_aliases" 
 "vim"
 "tmux.conf" 
@@ -30,44 +21,40 @@ declare -a files=(
 "Xresources" "xinitrc"
 )
 
-echo "Creating $olddir for backup of any existing dotfiles in ~"
+echo -e "${YELLOW}Creating $olddir for backup of any existing dotfiles in home and copy files${NC}"
 mkdir -p $olddir
 for file in "${files[@]}"; do
+    printf %b "   .$file..."
     if [ ! -f ~/.$file ]; then 
         cd $dir
         cd ~
         mv .$file $olddir
-        echo "Creating symlink to $file in `pwd`"
         ln -s $dir/$file .$file &> /dev/null
+        printf %b "${GREEN} OK${NC}\n"
+    else
+        printf %b "${YELLOW} skipped${NC}\n"
     fi;
 done
 
 # Install VIM config
+echo -e "${YELLOW}Installing vim configs...${NC}"
 declare -a files=(
-"vimrc" "nvimrc" 
+"vimrc" 
 )
 cd ~
 for file in "${files[@]}"; do
+    printf %b "   .$file...${NC}"
     if [ ! -f ~/.$file ]; then 
         ln -s $dir/vimconfig .$file &> /dev/null
+        printf %b "${GREEN} OK${NC}\n"
+    else
+        printf %b "${YELLOW} skipped${NC}\n"
     fi;
 done
 
-vim +PlugUpdate +qall
-
-# tern_for_vim requirements
-command -v npm &> /dev/null
-if [ $? = 0 ]; then 
-    pushd ~/.vim/plugged/tern_for_vim/
-    npm install
-    popd
-else
-    echo -e "${RED}*** ERROR: npm is not found${NC}"
-fi;
-
 # Install you-complete-me (VIM environments only)
-if [ ${USE_VIM} = 1 ]; then 
-    echo -e "Installing VIM stuff"
+if [ ${USE_NVIM} = 0 ]; then 
+    echo -e "${YELLOW}Installing VIM you complete me plugin...${NC}"
    # command -v cmake &> /dev/null
    # echo "Compiling YouCompleteMe binaries..."
    # command -v cmake &> /dev/null
@@ -78,14 +65,86 @@ if [ ${USE_VIM} = 1 ]; then
    # else
    #     echo -e "${RED}*** ERROR: cmake is not found${NC}"
    # fi;
+
+   # vim +PlugUpdate +qall
 fi;
 
+#install git-completion
+printf %b "${YELLOW}Installing git completion...${NC}"
+if [ ! -f $dir/git-completion.bash ]; then 
+    cd $dir
+    curl https://raw.github.com/git/git/master/contrib/completion/git-completion.bash -OLs > /dev/null
+    printf %b "${GREEN} OK${NC}\n"
+else
+    printf %b "${YELLOW} skipped${NC}\n"
+fi;
 
-echo "Executing vim colorscheme install..."
-exec $dir/vim/colors/install_colors
+# install GTK3 config
+printf %b "${YELLOW}Disabling f10 for gnome-menu...${NC}"
+unamestr=`uname`
+if [[ "$unamestr" == 'Linux' ]]; then 
+    GNOME_CONFIG=".config/gtk-3.0"
+    mkdir ~/$GNOME_CONFIG -p
+    if [ ! -f ~/$GNOME_CONFIG/gtk.css ]; then 
+        ln -s $dir/$GNOME_CONFIG/gtk.css ~/$GNOME_CONFIG/gtk.css
+        printf %b "${GREEN} OK${NC}\n"
+    else
+        printf %b "${YELLOW} skipped${NC}\n"
+    fi;
+fi;
 
-# install VIM-NVIM transistion
+# Install sjl/t [minimalistic tasks! <3]
+printf %b "${YELLOW}Installing minimalisic task manager [http://stevelosh.com/projects/t]...${NC}"
+command -v t &> /dev/null
+if [ $? = 127 ]; then 
+    git clone https://github.com/sjl/t.git ~/.tasks/t  
+    printf %b "${GREEN}OK${NC}\n"
+else
+    printf %b "${YELLOW}skipped${NC}\n"
+fi;
+
+# Install vim fancy colors
+echo -e "${YELLOW}Installing vim colorschemes...${NC}"
+bash $dir/vim/colors/install_colors
+
+printf %b "${YELLOW}Creating nvim config...${NC}"
+if [ ! -f ~/.vim/init.vim ]; then 
+cat <<'EOF' > ~/.vim/init.vim
 set runtimepath^=~/.vim runtimepath+=~/.vim/after
 let &packpath = &runtimepath
 source ~/.vimrc
+EOF
+    printf %b "${GREEN}OK${NC}\n"
+else
+    printf %b "${YELLOW}skipped${NC}\n"
+fi;
 
+# Installing python debugging protocol for vim-vdebug
+# Usage: python-debug <script.py>
+printf %b "${YELLOW}Installing python debugging tool for vdebug...${NC}"
+if [ ! -f ~/.local/bin/python-debug ]; then 
+    cd /tmp && wget -qO- http://downloads.activestate.com/Komodo/releases/10.2.3/remotedebugging/Komodo-PythonRemoteDebugging-10.2.3-89902-linux-x86_64.tar.gz > /dev/null | tar xvz && mv /tmp/Komodo-PythonRemoteDebugging-10.2.3-89902-linux-x86_64/ ~/.python-debugger-client && mv ~/.python-debugger-client/pythonlib/dbgp ~/.python-debugger-client/
+cat <<'EOF' > ~/.local/bin/python-debug
+#!/bin/bash
+python -S ~/.python-debugger-client/pydbgp -d localhost:9000 "$@"
+EOF
+    chmod +x ~/.local/bin/python-debug
+        printf %b "${GREEN} OK${NC}\n"
+    else
+        printf %b "${YELLOW} skipped${NC}\n"
+fi;
+
+
+# tern_for_vim requirements
+printf %b "${YELLOW}Installing tern_for_vim deps...${NC}\n"
+command -v npm &> /dev/null
+if [ $? = 0 ]; then 
+    pushd ~/.vim/plugged/tern_for_vim/ > /dev/null
+    npm install
+    popd > /dev/null
+    printf %b "${GREEN}OK${NC}\n"
+else
+    printf %b "${RED}*** ERROR: npm is not found${NC}\n"
+fi;
+
+printf %b "${GREEN}Finished.${NC}\n"
