moar configs

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,4 +1,7 @@
 #!/bin/bash
+# Helper ANSI colors
+RED='\033[0;31m'
+NC='\033[0m' # No Color
 
 # creates symlinks for desired files from home to specified directory
 
@@ -7,8 +10,7 @@ olddir=~/.dotfiles.bak
 
 # install GTK3 config
 unamestr=`uname`
-if [[ "$unamestr" == 'Linux' ]]; then
-    GNOME_CONFIG=".config/gtk-3.0"
+if [[ "$unamestr" == 'Linux' ]]; then GNOME_CONFIG=".config/gtk-3.0"
     mkdir ~/$GNOME_CONFIG -p
     ln -s $dir/$GNOME_CONFIG/gtk.css ~/$GNOME_CONFIG/gtk.css
 fi;
@@ -42,6 +44,29 @@ for file in "${files[@]}"; do
 done
 
 vim +PlugUpdate +qall
+
+# tern_for_vim requirements
+echo "Installing tern_for_vim dependencies..."
+command -v npm &> /dev/null
+if [ $? = 0 ]; then 
+    pushd ~/.vim/plugged/tern_for_vim/
+    npm install
+    popd
+else
+    echo -e "${RED}*** ERROR: npm is not found${NC}"
+fi;
+
+# Install you-complete-me
+echo "Compiling YouCompleteMe binaries..."
+command -v cmake &> /dev/null
+if [ $? = 0 ]; then 
+    pushd ~/.vim/plugged/YouCompleteMe
+    ./install.py --tern-completer
+    popd
+else
+    echo -e "${RED}*** ERROR: cmake is not found${NC}"
+fi;
+
 
 echo "Executing vim colorscheme install..."
 exec $dir/vim/colors/install_colors
